import Head from 'next/head'

const MainLayout = ({ children }) => {
    return (
        <div className="flex flex-col">
            <Head>
                <title>Sale page wiseskin</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="flex justify-center">
                {children}
            </main>

            <footer className="flex">

            </footer>
        </div>
    )
}

export default MainLayout